### ISSUE TITLE
Update dataset failed 

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/shareloc-collection#26] opened 2022-10-10 18:34 UTC
Dear @oeway,
After editing the dataset, this [workflow](https://github.com/imodpasteur/shareloc-collection/actions/runs/3221508325/jobs/5269590247) failed to update the new version, seems to be bad connection with zendo
I tried to revert the commits but failed too :(
Thank you in advance,

**Comment by oeway** [comment] 2022-10-11 14:46
Hi @baiddd The issue is caused by recently merged PRs. I had a look at these items, I guess it's because the rdf.yaml file was not updated with the newly uploaded files. For example this one: https://zenodo.org/record/7182224

In the yaml file, the sample name is `NPC_gp210-Alexa-647` while the actual files is named `gp210_647_4`.  You can fix it  by modify the yaml and upload it as a new version on zenodo, just to make sure the sample name match the actual file names.

Did you use the edit feature to upload it?

**Comment by oeway** [comment] 2022-10-11 14:56
FYI: I just updated the yaml file here: https://zenodo.org/record/7185997 manually with a new version, now it seems to be working.

To prevent future issues, I have enabled CI for every automatic CI (it was disabled by github to prevent circular triggering of CI), so please make sure the CI passes when you merge new automatic PRs.

**Comment by oeway** [comment] 2022-10-11 14:58
Closing this now

**Closed by oeway** 2022-10-11 14:58 UTC
